### ISSUE TITLE
Design: Support User bundle build in singularity 

### ISSUE THREAD

**Issue by rosibaj** [cancogen-virus-seq/singularity#13]
- accept a set-id from arranger (learn how the arranger set is delivered)  
- translate the documented in set-id into a user bundle 
- add new table to track user bundle tracking [similar to archive bundle] 
- document design across services in wiki for implementation in the following sprint

**Comment by lepsalex** [comment]
Unified design with download all archive, specific considerations for dynamic downloads included:

https://wiki.oicr.on.ca/display/OV/CanCoGen+Virus+Seq+Data+Portal#CanCoGenVirusSeqDataPortal-4.4VirusSeqDataDownloadandAggregationService
