### ISSUE TITLE
BUG - Bundles stuck building

### ISSUE THREAD

**Issue by jaserud** [cancogen-virus-seq/singularity#28]
- singularity stops building an archive bundle if it recieves a signal for updates in the portal, but it looks like the archive remains stuck as BUILDING in the db
- bundles can also be stuck building if the app restarts mid building
- can see a bunch of archives are just stuck here: https://singularity.virusseq-dataportal.ca/archives?sortDirection=DESC&sortField=createdAt&status=BUILDING&size=1 (look for `totalElements`)
- we should either delete these or mark them as CANCELLED
- might also want to add an endpoint to manually remove archives that get stuck for other reasons

This behaviour has also been notcied with SET_QUERY bundles: https://singularity.virusseq-dataportal.ca/archives?status=BUILDING&type=SET_QUERY

**Comment by akachru-github** [comment]
@jaserud is this a blocker or cause of a current critical bug of any kind at the moment?

**Comment by jaserud** [comment]
With this bug if an archive gets stuck in BUILDING and Singularity isn't actually building it, any attempts to download that will be stuck loading forever. I  think that scenario is not very likely though, since I only noticed it last week. But until we address this, archive that are stuck won't download until we actually go into the DB and delete the record or the ES data updates and singularity ignores the old one as being stale and starts a new BUILDING archive.

**Comment by sifavahora** [comment]
@joneubank @UmmulkiramR  can you please confirm does this has anything to do with https://github.com/cancogen-virus-seq/portal/issues/254

**Comment by sifavahora** [comment]
Debugging guidelines by Jaser - https://wiki.oicr.on.ca/display/OV/Fix+latest+release+data+not+being+created

**Comment by sifavahora** [comment]
I think this is the same issue that fails downloads with duplicate Hash  exception. we want to fix this

**Comment by UmmulkiramR** [comment]
@sifavahora 
From what I understand from the description, this ticket talks about 
1. Correctly updating the status of the archive entry :
      Mark the status as FAILED, CANCELLED OR COMPLETE. The system does mark the archives as FAILED and COMPLETE 
      appropriately. We need to check if updating status as CANCELLED can be achieved.
2. Providing an endpoint for cleaning up all archive entries stuck in BUILDING :
      The duplicate hash key issue occurs when the system tries to rebuild the archive that is stuck in BUILDING. The clean up 
      should solve this problem.

**Comment by sifavahora** [comment]
After analyzing the complete scenario and various edge cases, we concluded on doing the following: 
- [ ] Create a Cancel Archive Endpoint  - cancel archive stuck in building for 4+ hours
- [ ]  Create a Force Cancel Endpoint - manually force cancel any Build
- [ ] tag killed builds as `CANCELLED` in db for `ArchiveType =ALL`
