### ISSUE TITLE
TSV creation fails due to array fields

### ISSUE THREAD

**Issue by caravinci** [cancogen-virus-seq/singularity#43]
As found on the logs, Singularity expects a string from Elasticsearch for a few fields that have been updated into arrays.
These fields in the tsv are all hardcoded, and there should be a way to specify not just the fields but their type (similar to how we do in Arranger)
![image.png](https://images.zenhubusercontent.com/5defce3f99bcf0b1b8a98d24/ec2fc910-dd33-4f4a-9348-f5cf154baadd)

**Comment by sifavahora** [comment]
This fails the release bundle building in turn
