### ISSUE TITLE
Tests, Tests, Tests

### ISSUE THREAD

**Issue by rosibaj** [cancogen-virus-seq/singularity#5]
Integrations:
- Test object storage connections
- Test errors being handled correctly 
- Jenkins / Maven updates required

**Potentially** include e2e tests. But this is a lower priority as we have manual tests to cover this: 
- end-to-end bundle building, all connections

Environment:
- We can hit the DEV bucket to support these tests
  - Using the DEV env, we could write some comprehensive tests

**Comment by andricDu** [comment]
no further tests needed.
