### ISSUE TITLE
Store total counts in database instead of server memory 

### ISSUE THREAD

**Issue by sifavahora** [cancogen-virus-seq/singularity#51]
Current Scenario: the total counts (API link ) is stored in the serve memory and is refreshed every time there is an upload/delete of samples on the portal. 

Problem with this: When we have multiple pods running for singularity, different pods save different count based on the pod handling the request at the time of upload. i.e the other pods will not update their count. 

Expected Scenario: We want to save the total count of files in the database in a new table in Singularity and have Singularity return the value of total counts from the database instead of memory.

**Comment by caravinci** [comment]
This endpoint is how Singularity offers the counts: https://singularity.virusseq-dataportal.ca/aggregations/total-counts
Pasting it here in case it helps tracing down the counting logic.

**Comment by lrivera-oicr** [comment]
In order to persist data in database, a new table has been created **total_count** with following columns: 

- id uuid
- files bigint
- samples int
- studies bigint
- file_size_bytes bigint
- file_size_human_readable varchar
- timestamp bigint

**Comment by lrivera-oicr** [comment]
Database change applied and code change merged and deployed in DEV.
