### ISSUE TITLE
duplicate HASH key on a new SET_QUERY building

### ISSUE THREAD

**Issue by lrivera-oicr** [cancogen-virus-seq/singularity#53]
This is part II of [issue#28](https://app.zenhub.com/workspaces/cancogen-virus-seq-61d8aeee334b9200185d6283/issues/cancogen-virus-seq/singularity/28)

**Issue:** getting error _duplicate key value violates unique constraint "archive_hash_key"_ when a new SET_QUERY comes up and hash matches.

**Proposed solution:**
if a new SET_QUERY comes up, and the hash matches one building that is on CANCELLED status OR has 4+ hours old in BUILDING status,  then: 

 **- tag it/keep it as BUILDING in database**
 **- update created_at field with current date**
 **- start over a the building process**

**Comment by caravinci** [comment]
will this ticket include the handling of `BUILDING and <4 hours old`?

**Comment by lrivera-oicr** [comment]
if `BUILDING and <4 hours old` it shouldn't alter the building process or update database.

**Comment by lrivera-oicr** [comment]
I guess no need to change the existing logic if BUILDING is less than 4h old, hence it won't initiate to build a new archive and the API response will be the same as it  is right now, i.e. returns the existing building record as the response.

**Comment by caravinci** [comment]
I mean if two different clients ask for the same hash. you mean that is handled already?

**Comment by lrivera-oicr** [comment]
yes it's handled already.
