### ISSUE TITLE
Delete temp file(archive) when archive build fails. 

### ISSUE THREAD

**Issue by sifavahora** [cancogen-virus-seq/singularity#64]
Current Behavior: 
When an archive build fails, the (incomplete)temp file stays in the pod as it is. this causes a file overwrite error when retrying to build the archive. 

Expected Behavior: 
When an archive build fails, Status = Failed/Cancelled, the temp file should be deleted from the pod to avoid any file overwrite error when retrying to build archive. 

@caravinci  feel free to add suggestions on changing logs if need be (Duplicate key vs tmp file overwrite)

**Comment by lrivera-oicr** [comment]
cleaning up download directory and compressed file if exist before starting new download.
