### ISSUE TITLE
Kill archive build

### ISSUE THREAD

**Issue by lrivera-oicr** [cancogen-virus-seq/singularity#70]
Issue Description: 
force-cancel endpoint is not completely stopping an archive build process. 

Acceptance criteria:
- force-cancel endpoint must stop an archive build process of the specified hashId
- force-cancel endpoint must tag archive as CANCELLED on database
- cancel endpoint no changes. Business as usual.

**Comment by lrivera-oicr** [comment]
1. on force-cancel endpoint with no hashes passed on request.
2. find the latest BUILDING type ALL from the database
3. tag it as CANCELLED  on the database
4. stop if there is a build running on that pod.

**Comment by lrivera-oicr** [comment]
testing scenarios:

1. Start Build and Cancel on same pod
Start build: (pod A)
- [ ] create a record in DB as BUILDING
- [ ] Building archive in /tmp folder
Cancel build: (pod A)
- [ ] update record in DB as CANCELLED
- [ ] Stop building archive in /tmp folder

2. Start Build and Cancel on different pod  
Start build: (pod A)
- [ ] create a record in DB as BUILDING
- [ ] Building archive in /tmp folder
Cancel build: (pod B)
- [ ] update record in DB as CANCELLED
(pod A)
- [ ] After build completes do not update database record as COMPLETED.

**Comment by leoraba** [comment]
Change completed in branch name: kill_archive_build.
Still not merged in develop until further notice.

**Comment by leoraba** [comment]
merged into **main** branch.
