### ISSUE TITLE
Add Lineage columns and updated_at to singularity download

### ISSUE THREAD

**Issue by sifavahora** [cancogen-virus-seq/singularity#75]
Add the 6 lineage columns + updated_at to singularity tsv download. 
Use the same naming convention and order of columns as metadata only download

**Comment by lrivera-oicr** [comment]
verify all columns are in the same order and same title name than in Metadata only

**Comment by leoraba** [comment]
change is completed in branch name: **lineage_assignment**

**Comment by leoraba** [comment]
Still not merged in to develop branch. until further notice.

**Comment by leoraba** [comment]
merge into **master** branch.
